### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create HTML skeleton, set meta tags
- [x] add a main to the body where the car will load
- [x] add an img and give it's src attribute the path to the car
- [x] create a styles.css and link it
- [x] style the HTML to get the background and correct size/position for the car
