### ISSUE TITLE
User can turn the car

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create a main.js for the javascript
- [x] add a custom data field to the car for direction
- [x] add object model in main.js for car direction (not needed)
- [x] add classes for car direction and transform/transition for the changes
- [x] create script for changing the data field on the html based on event details
- [x] add listener for keydown on arrow keys and pass in the key info to the callback function
