### ISSUE TITLE
Issue 3 - User can start the car

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add absolute positioning to the CSS
- [x] add custom data attributes for coordinates
- [x] add script to move the car 
- [x] add interval (16ms) to run the movement script

**Comment by easton-morris** [comment]
![gocargo](https://user-images.githubusercontent.com/75236087/124222660-056f9080-dab7-11eb-80f2-e1c1b4ded470.gif)
