### ISSUE TITLE
Issue 4 User can stop car

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/driving-game#7]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a variable for whether the car is stopped or started
- [x] Add a logic gate in the move script
- [x] Add the additional consideration to the listener
